apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: authentication
  name: authentication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: authentication
    spec:
      containers:
      - image: de.icr.io/shopping/authentication
        name: authentication
        env:
          - name: APPID_OAUTHSERVERURL
            value: "https://eu-de.appid.cloud.ibm.com/oauth/v4/XXX"
          - name: APPID_CLIENTID
            value: "XXX"
          - name: APPID_SECRET
            value: "XXX"
          - name: REDIRECT_URL_CALLBACK
            value: "http://localhost:3000/callback"
          - name: REDIRECT_URL_WEB_APP
            value: "http://localhost:8080/loginwithtoken"
          - name: INSTANA_SERVICE_NAME
            value: "authentication_nodejs"
          - name : INSTANA_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: authentication
  name: authentication
spec:
  ports:
  - name: 3000-3000
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: authentication
  type: LoadBalancer
status:
  loadBalancer: {}
